# Generated by Django 5.2.4 on 2025-07-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='review_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество отзывов'),
        ),
    ]
